modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/TheMCBrothers/PuddingMod/issues"

[[mods]]
	modId="puddingmod"
	version="${file.jarVersion}"
	displayName="Pudding Mod"
	updateJSONURL="https://raw.githubusercontent.com/TheMCBrothers/Version/master/puddingmod_update.json"
	# displayURL="https://themcbros.tk/puddingmod/"
	logoFile="puddingmod.png"
	# credits="Thanks for this example mod goes to Java"
	authors="TheMCBrothers"
	
	description='''
	This mod adds pudding to minecraft!
	'''

[[dependencies.puddingmod]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.puddingmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
